version: "3.9"
services:
  python:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "3.11.7"
        PYTHON_VERSION: "3.11.7"
        PYTHON_RELEASE: "r1"
      context: .
      dockerfile: container.build
      tags:
        - "python:build"
        - "gautada/python:build"
        - "gautada/python:latest"
    image: "gautada/python:latest"
    hostname: "python"
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"
          
volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"

  Secrets:
    external: true
    name: "Secrets"
