kind: pipeline
type: exec
name: CICD - Python Container

platform:
  os: linux
  arch: arm64

steps:

- name: build
  commands:
  - /usr/bin/podman-compose build --no-cache
  
- name: test
  environment:
	DOCKERIO_USERNAME:
	  from_secret: username.docker.io
	DOCKERIO_PASSWORD:
	  from_secret: password.docker.io
  commands:
  - /usr/bin/podman run --interactive --rm --tty $(/usr/bin/compose-data --name):dev -- /usr/bin/container-test
  - /usr/bin/podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - /usr/bin/podman tag $(/usr/bin/compose-data --name):dev docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):dev
  - /usr/bin/podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):dev
  
- name: integrate
  environment:
	DOCKERIO_USERNAME:
	  from_secret: username.docker.io
	DOCKERIO_PASSWORD:
	  from_secret: password.docker.io
  commands:
  - /usr/bin/podman tag $(/usr/bin/compose-data --name):dev docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):$(/usr/bin/compose-data --version)
  - /usr/bin/podman tag $(/usr/bin/compose-data --name):dev docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):latest
  - /usr/bin/podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - /usr/bin/podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):latest
  - /usr/bin/podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-data --name):$(/usr/bin/compose-data --version)
  when:
	branch:
	- main


- name: deploy
  failure: ignore
  environment:
	DRONE_SERVER:
	  from_secret: server.drone.io
	DRONE_TOKEN:
	  from_secret: token.drone.io
  commands:
  - /usr/bin/drone build create --branch main gautada/drone-container
  - /usr/bin/drone build create --branch main gautada/gitea-container
  - /usr/bin/drone build create --branch main gautada/postgresql-container
  when:
	branch:
	- main
	
trigger:
  event:
  - push

