#!/bin/sh
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

container_version() {
 echo "0.0.0"
}

container_entrypoint() {
 cd /mnt/volumes/container
 /home/python/.local/bin/jupyter-server --port 8080 --no-browser --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''
}
