#!/bin/ash
#
# This is entrypoint should launch the container service when a command is not
# provided in an `exec` script.
#
# This is the script for the wetty interface which proivides a cli via a web browser.

# WETTY_USER=python
# WETTY_TITLE="Python Development Client"
#
# echo "---------- [ WETTY INTERFACE($WETTY_USER) ] ----------"
#
# Make the server ssh key on start
# if [ ! -f "/etc/ssh/ssh_host_rsa_key" ] ; then
#  /usr/bin/sudo /usr/bin/ssh-keygen -A -t rsa -N ''
# fi
# Launch the ssh daemon
# /usr/bin/sudo /usr/sbin/sshd
# Setup the local ssh keys
# if [ ! -f /home/$WETTY_USER/.ssh/id_rsa ] ; then
#  /bin/mkdir /home/$WETTY_USER/.ssh
#  /bin/chmod 700 /home/$WETTY_USER/.ssh
#  /usr/bin/ssh-keygen -t rsa -N '' -f /home/$WETTY_USER/.ssh/id_rsa
#  /bin/cp /home/$WETTY_USER/.ssh/id_rsa.pub /home/$WETTY_USER/.ssh/authorized_keys
#  /bin/chmod 600 /home/$WETTY_USER/.ssh/authorized_keys
# fi
# # Launch the wetty interface
# if [ -z "$ENTRYPOINT_PARAMS" ] ; then
#  /home/$WETTY_USER/.yarn/bin/wetty --port 8080 --ssh-host localhost --ssh-user $WETTY_USER --ssh-auth publickey --ssh-key /home/$WETTY_USER/.ssh/id_rsa --force-ssh --title $WETTY_TITLE --command /bin/ash
# /usr/bin/python3
# /home/$WETTY_USER/.local/bin/aws-shell
# fi
# return 0

app_entrypoint() {
 cd /mnt/volumes/container
 /home/python/.local/bin/jupyter-server --port 8080 --no-browser --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''
}
