#!/bin/sh
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

container_version() {
 /usr/bin/python --version | awk -F ' ' '{print $2}'
}

container_entrypoint() {
 cd $HOME/jupyter
 /home/python/.local/bin/jupyter-server -y --port 8080 --no-browser --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'
}
